GET http://localhost:3003/api/blogs

###

DELETE http://localhost:3003/api/blogs/68e779b819d6aa6ffc994cc6

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "dani",
    "author": "danivagyok",
    "url": "url",
    "likes": 10
}